/*
The next code was generated by Repository Pattern Generator.
Be free to modify this file.

This extension was developed and designed by Francisco López Sánchez.
*/

using System;

namespace DataModel.ViewModel
{
    public class FicheroModel
    {
        public int Id { get; set; }
        //public int IdTarea { get; set; }
        //public string Tipo { get; set; }
        public string Nombre { get; set; }
    }
}
