/*
The next code was generated by Repository Pattern Generator.
Be free to modify this file.

This extension was developed and designed by Francisco López Sánchez.
*/

using System;

namespace DataModel.ViewModel
{
    public class TareaModel
    {
        public int Id { get; set; }
        public int IdUsuario { get; set; }
        public int IdGrupo { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public string Ubicacion { get; set; }
        public System.DateTime Fecha { get; set; }
        public bool Finalizada { get; set; }
    }
}
