/*
The next code was generated by Repository Pattern Generator.
Be free to modify this file.

This extension was developed and designed by Francisco López Sánchez.
*/

using Repository.Model;
using DataModel.ViewModel;

namespace Repository.Adapter
{
    public class FicheroAdapter : Adapter<Fichero, FicheroModel>
    {
        public override Fichero FromViewModel(FicheroModel model)
        {
            return new Fichero()
            {
                Id = model.Id,
                //IdTarea = model.IdTarea,
                //Tipo = model.Tipo,
                Nombre = model.Nombre
            };
        }

        public override FicheroModel FromModel(Fichero model)
        {
            return new FicheroModel()
            {
                Id = model.Id,
                //IdTarea = model.IdTarea,
                //Tipo = model.Tipo,
                Nombre = model.Nombre
            };
        }
    }
}
