/*
The next code was generated by Repository Pattern Generator.
Be free to modify this file.

This extension was developed and designed by Francisco López Sánchez.
*/

using Repository.Model;
using DataModel.ViewModel;

namespace Repository.Adapter
{
    public class GrupoAdapter : Adapter<Grupo, GrupoModel>
    {
        public override Grupo FromViewModel(GrupoModel model)
        {
            return new Grupo()
            {
                Id = model.Id,
                IdUsuario = model.IdUsuario,
                Nombre = model.Nombre
            };
        }

        public override GrupoModel FromModel(Grupo model)
        {
            return new GrupoModel()
            {
                Id = model.Id,
                IdUsuario = model.IdUsuario,
                Nombre = model.Nombre
            };
        }
    }
}
