/*
The next code was generated by Repository Pattern Generator.
Be free to modify this file.

This extension was developed and designed by Francisco López Sánchez.
*/

using Repository.Model;
using DataModel.ViewModel;

namespace Repository.Adapter
{
    public class TareaAdapter : Adapter<Tarea, TareaModel>
    {
        public override Tarea FromViewModel(TareaModel model)
        {
            return new Tarea()
            {
                Id = model.Id,
                IdGrupo = model.IdGrupo,
                Titulo = model.Titulo,
                Descripcion = model.Descripcion,
                Ubicacion = model.Ubicacion,
                Fecha = model.Fecha,
                Finalizada = model.Finalizada
            };
        }

        public override TareaModel FromModel(Tarea model)
        {
            return new TareaModel()
            {
                Id = model.Id,
                IdGrupo = model.IdGrupo,
                Titulo = model.Titulo,
                Descripcion = model.Descripcion,
                Ubicacion = model.Ubicacion,
                Fecha = model.Fecha,
                Finalizada = model.Finalizada
            };
        }
    }
}
