/*
The next code was generated by Repository Pattern Generator.
Be free to modify this file.

This extension was developed and designed by Francisco López Sánchez.
*/

using System.Data.Entity;
using Repository.Adapter;
using Repository.Model;
using Repository.Repository;
using DataModel.ViewModel;

namespace ApiGestionDeTareas.Repository
{
    public class GrupoRepository : EntityFrameworkRepository<Grupo, GrupoModel, GrupoAdapter>
    {
        public GrupoRepository(DbContext context) : base(context) { }
    }
}
