//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fichero
    {
        public int Id { get; set; }
        public int IdTarea { get; set; }
        public string Tipo { get; set; }
        public string Nombre { get; set; }
    
        public virtual Tarea Tarea { get; set; }
    }
}
